//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_console_app.MessageServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Arbetsprov_Atea_Jean_Kam_2015", ConfigurationName="MessageServiceReference.MessageServiceSoap")]
    public interface MessageServiceSoap {
        
        // CODEGEN: Generating message contract since element name msg from namespace Arbetsprov_Atea_Jean_Kam_2015 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Arbetsprov_Atea_Jean_Kam_2015/SaveMessage", ReplyAction="*")]
        The_console_app.MessageServiceReference.SaveMessageResponse SaveMessage(The_console_app.MessageServiceReference.SaveMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Arbetsprov_Atea_Jean_Kam_2015/SaveMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<The_console_app.MessageServiceReference.SaveMessageResponse> SaveMessageAsync(The_console_app.MessageServiceReference.SaveMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveMessage", Namespace="Arbetsprov_Atea_Jean_Kam_2015", Order=0)]
        public The_console_app.MessageServiceReference.SaveMessageRequestBody Body;
        
        public SaveMessageRequest() {
        }
        
        public SaveMessageRequest(The_console_app.MessageServiceReference.SaveMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Arbetsprov_Atea_Jean_Kam_2015")]
    public partial class SaveMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string msg;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime date;
        
        public SaveMessageRequestBody() {
        }
        
        public SaveMessageRequestBody(string msg, System.DateTime date) {
            this.msg = msg;
            this.date = date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveMessageResponse", Namespace="Arbetsprov_Atea_Jean_Kam_2015", Order=0)]
        public The_console_app.MessageServiceReference.SaveMessageResponseBody Body;
        
        public SaveMessageResponse() {
        }
        
        public SaveMessageResponse(The_console_app.MessageServiceReference.SaveMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Arbetsprov_Atea_Jean_Kam_2015")]
    public partial class SaveMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SaveMessageResult;
        
        public SaveMessageResponseBody() {
        }
        
        public SaveMessageResponseBody(int SaveMessageResult) {
            this.SaveMessageResult = SaveMessageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MessageServiceSoapChannel : The_console_app.MessageServiceReference.MessageServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageServiceSoapClient : System.ServiceModel.ClientBase<The_console_app.MessageServiceReference.MessageServiceSoap>, The_console_app.MessageServiceReference.MessageServiceSoap {
        
        public MessageServiceSoapClient() {
        }
        
        public MessageServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessageServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        The_console_app.MessageServiceReference.SaveMessageResponse The_console_app.MessageServiceReference.MessageServiceSoap.SaveMessage(The_console_app.MessageServiceReference.SaveMessageRequest request) {
            return base.Channel.SaveMessage(request);
        }
        
        public int SaveMessage(string msg, System.DateTime date) {
            The_console_app.MessageServiceReference.SaveMessageRequest inValue = new The_console_app.MessageServiceReference.SaveMessageRequest();
            inValue.Body = new The_console_app.MessageServiceReference.SaveMessageRequestBody();
            inValue.Body.msg = msg;
            inValue.Body.date = date;
            The_console_app.MessageServiceReference.SaveMessageResponse retVal = ((The_console_app.MessageServiceReference.MessageServiceSoap)(this)).SaveMessage(inValue);
            return retVal.Body.SaveMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<The_console_app.MessageServiceReference.SaveMessageResponse> The_console_app.MessageServiceReference.MessageServiceSoap.SaveMessageAsync(The_console_app.MessageServiceReference.SaveMessageRequest request) {
            return base.Channel.SaveMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<The_console_app.MessageServiceReference.SaveMessageResponse> SaveMessageAsync(string msg, System.DateTime date) {
            The_console_app.MessageServiceReference.SaveMessageRequest inValue = new The_console_app.MessageServiceReference.SaveMessageRequest();
            inValue.Body = new The_console_app.MessageServiceReference.SaveMessageRequestBody();
            inValue.Body.msg = msg;
            inValue.Body.date = date;
            return ((The_console_app.MessageServiceReference.MessageServiceSoap)(this)).SaveMessageAsync(inValue);
        }
    }
}
